- src/components/cue-point/cue-point.js
Please add a detailed description of the change, weather it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.
> fix(FEV-1392): use timeline marker width and height if doesn't exist on preview object

- src/components/marker/timeline-preview.scss
add `max-width: 320px` to the preview title element per design.
Solves [FEC-13337](https://kaltura.atlassian.net/browse/FEC-13337)
[FEC-13337]: https://kaltura.atlassian.net/browse/FEC-13337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(FEC-13337): preview title with too many characters is not shown properly

- src/components/marker/timeline-preview.tsx
**the issue:**
when voiceOver is enabled and focusing on a timeline preview header title, the voiceover also focuses on the seekbar element.
**fix:**
change the role of the seekbar element from `slider` to `none` and vice-versa on `focus` and `blur` of `timelinePreview` component.
Solves [FEC-13331](https://kaltura.atlassian.net/browse/FEC-13331)
[FEC-13331]: https://kaltura.atlassian.net/browse/FEC-13331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(FEC-13331): handle seekbar a11y when timeline preview is focused

- src/components/marker/timeline-preview.tsx
handle timeline preview title when there's no thumbnail.
Solves [FEC-13336](https://kaltura.atlassian.net/browse/FEC-13336)
[FEC-13336]: https://kaltura.atlassian.net/browse/FEC-13336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(FEC-13336): handle preview title when there is no thumbnail

- src/components/marker/timeline-preview.scss
remove `max-width` for header element- it causes the hover to be shorter than the text.
> fix(FEC-13337): fix hover width on title preview

- src/components/chapters/seekbar-segment.js
- src/components/chapters/seekbar-segment.scss
- src/components/chapters/segments-wrapper.js
- src/components/cue-point/cue-point.js
- src/components/marker/timeline-marker.scss
- src/components/marker/timeline-preview.scss
- src/components/marker/timeline-preview.tsx
- src/timeline-manager.tsx
- src/types/timelineTypes.ts
solves: https://kaltura.atlassian.net/browse/FEC-13017
In case of dual-screen plugin exist - replace default preview component to custom one that uses thumb-preview API of dual-screen plugin
Related PR: https://github.com/kaltura/playkit-js-dual-screen/pull/117
> feat(FEC-13017): add dua-screen thumbnails on the timeline

- cypress/e2e/timeline.cy.ts
- src/components/chapters/segments-wrapper.js
- src/timeline-manager.tsx
- src/timeline.js
**the issue:**
in playlist, when switching between entries that have segments on timeline (chapters), sometimes the `duration` state of the engine isn't getting updated fast enough, with the new correct value of the new entry, before the `segmentsWrapper` is setting the duration to the last segment. Hence, sometimes the duration of the last segment is incorrect and as a result, the calculation of the timeline progress is being affected.
**solution:**
make sure the duration is correct and stable, before adding the kaltura cue points.
Solves [FEC-13424](https://kaltura.atlassian.net/browse/FEC-13424)
[FEC-13424]: https://kaltura.atlassian.net/browse/FEC-13424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(FEC-13424): timeline segments issue with playlist

- src/timeline-manager.tsx
**issue:**
markers are not displayed on the timeline when video duration is higher than X.5.
**solution:**
Round the video duration with Math.round instead of Math.floor cause backend returns the duration also with Math.round so need to be aligned. 
solves [SUP-40702](https://kaltura.atlassian.net/browse/SUP-40702)
[SUP-40702]: https://kaltura.atlassian.net/browse/SUP-40702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(SUP-40702): Video quiz is not showing quePoints

- src/timeline-manager.tsx
- **bugfix**
**the issue:**
sometimes markers/chapters are not shown on timeline.
**root cause:**
when checking if the duration is correct, it is possible that `seekFrom` has value of `0`.
currently, when the value is 0, the logic breaks and the new calculation for duration is not happening. As a result, the duration is never correct and `timelineDurationPromise` is never resolved. This affect rendering cuepoints on timeline.
**solution:**
validate `typeof seekFrom`.
Solves [FEC-13628](https://kaltura.atlassian.net/browse/FEC-13628)
[FEC-13628]: https://kaltura.atlassian.net/browse/FEC-13628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(FEC-13628): markers not shown on timeline for clipped video

- src/timeline-manager.tsx
add support for prevent seek.
if preventSeek is active, do not add cue points to timeline.
dependent on https://github.com/kaltura/kaltura-player-js/pull/747
Solves FEC-13492
> feat(FEC-13492): add support for prevent seek

- src/components/marker/timeline-preview.tsx
- src/timeline-manager.tsx
- Prevent timeline preview from using stopPropagation when using a dual screen preview, and keep it only for chapters preview
- Add shouldComponentUpdate for timeline preview, otherwise render is constantly triggered because thumbnailInfo reference changes on every get()
Resolves FEC-13779
> fix(FEC-13779): Thumbnails display when hovering over timeline is choppy

- src/components/marker/timeline-preview.scss
**Issue:**
Hover on timeline, gray dot is displayed above the thumbnail. 
**Root cause:**
This caused since added background to the header preview element so also in case there is no title (hotspot/quiz/answer) the element have the background.
**Fix:**
Add this style only if title element is exist inside the header element.
Solves [FEC-14101](https://kaltura.atlassian.net/browse/FEC-14101)
Player
[FEC-14101]: https://kaltura.atlassian.net/browse/FEC-14101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(FEC-14101): Player v7 | Hover on the timeline displays a black dot.

- src/components/marker/timeline-marker.tsx
- src/components/marker/timeline-preview.tsx
- src/timeline-manager.tsx
- src/types/timelineTypes.ts
resolves: https://kaltura.atlassian.net/browse/A11Y-58
> fix(A11Y-58): add aria-label to timeline marker

- package.json
- src/timeline-manager.tsx
- yarn.lock
**Issue:**
Markers are not shown on the player in youtube videos
**Root cause:** 
When retrieving video duration via the YouTube Data API, the duration is returned as a rounded-up value. this value is used when creating the YouTube entry (from kms)
In the player, we use the getDuration() function from the YouTube iframe API, which returns the duration as a floating number.
In timeline manager we compare the duration: entry.duration === round(engine.duration) so in case of youtube entry with duration less then X.5 it will never be true
**Fix:** 
If youtube entry is played, round up with ceil function
Resolved [SUP-43592](https://kaltura.atlassian.net/browse/SUP-43592)
[SUP-43592]: https://kaltura.atlassian.net/browse/SUP-43592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLC …
> fix(SUP-43592): [PSU] Cue Points not showing in some YT Ingested Video Quiz

- src/components/marker/timeline-preview.tsx
Issue:
When timeline plugin is activated and user hover on the seekbar, only the first thumbnail is shown all the time.
Root cause: 
Component is not rendered when user hover the seekbar since relevantChapter is always undefined 
Fix:
Adding the condition also check virtualTime change
Solves [SUP-45380](https://kaltura.atlassian.net/browse/SUP-45380)
[SUP-45380]: https://kaltura.atlassian.net/browse/SUP-45380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(SUP-45380): [Wells Fargo] Black thumbnail on scrubber

- src/components/marker/timeline-preview.scss
- src/components/marker/timeline-preview.tsx
issue:
when create audio entry with chapters, the chapters on the timeline and the time are on the same line
solution:
add case when there are thumbnails to fit the chapters css if there are thumbnail and if not.
solve [SUP-45037](https://kaltura.atlassian.net/browse/SUP-45037)
[SUP-45037]: https://kaltura.atlassian.net/browse/SUP-45037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(SUP-45037): [UMICH] Audio Entry Timestamp bug

- cypress/e2e/timeline.cy.ts
- cypress/e2e/utils.ts
- flow-typed/types/cue-point-option.ts
- src/components/chapters/segments-wrapper.scss
- src/components/marker/timeline-preview.tsx
- src/timeline-manager.tsx
- src/timeline.js
- src/types/timelineTypes.ts
1. create timeline manager API (instead of share entire service)
2. created API for dual-screen preview
3. add remove all cues method into API
4. chapters can have callback on header click
resolves: https://kaltura.atlassian.net/browse/CR-152
> feat(CR-152): add API for commit and restore cues

- src/timeline-manager.tsx
**bugfix - regression.**
**the issue:**
when loading a video with chapters, there are gaps in the progress of the timeline.
**root cause:**
since changes in [CR-152](https://github.com/kaltura/playkit-js-timeline/pull/47)- the timeline manager is not registered as a service anymore, so `reset()` is not being invoked when changing media. As a result, when switching media there are duplicated chapters (and timeline segments).
**solution:**
add `reset()` to `timelineManagerAPI` service.
Solves FEC-14300
[CR-152]: https://kaltura.atlassian.net/browse/CR-152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(FEC-14300): gaps in the timeline progress

- src/timeline-manager.tsx
- src/types/timelineTypes.ts
**the issue:**
when playkit-unisphere plugin loads summary & chapters widget, but the chapters data is empty, "regular" chapters are not shown on timeline (if exist).
**solution:**
- hold a new flag which indicates whether the timeline manager should or shouldn't add "regular" chapters to the timeline
- add a new API- `disableChapters`, which sets the value of the new flag and resets the chapters array in case that "regular" chapters were loaded already
- expose the api on `timelineManagerAPI`
- distinguish between a "regular" chapter and a summary chapter
- in `addKalturaCuePoint` api, if the incoming cuepoint is "Chapter" and the new flag indicates to not load chapters- then do not add it to the timeline
**additional fix:**
there's a missing use-case in `isDurationCorrect` logic, where …
> fix(FEC-14362): add disableChapters api

- src/timeline-manager.tsx
bug fix.
**the root cause:**
checking the flag `_shouldIncludeChapters` before the duration promise is resolved; if a chapter comes when `_shouldIncludeChapters` is `true` (before chapters were disabled), then it moves on to await for the duration promise. once the promise is resolved- it adds the chapter even though the chapters were disabled.
**the solution:**
check the `_shouldIncludeChapters` flag after duration promise is resolved.
Resolves FEC-14402
> fix(FEC-14402): timeline display both regular and summary chapters

- src/timeline-manager.tsx
**Issue:**
The cue-points of the IVQ questions are loaded when the ads are playing, therefore, they are not seen in the seek bar when the entry is playing.
**Fix:**
When all the ads are completed, remove all the cue-points and put them again, in order to see them on the seekbar.
solved [SUP-47479](https://kaltura.atlassian.net/browse/SUP-47479)
[SUP-47479]: https://kaltura.atlassian.net/browse/SUP-47479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix (SUP-47479): player with bumper prevents display of quiz timestamp on the timeline

- src/components/marker/timeline-preview.tsx
- translations/en.i18n.json
This solves this https://kaltura.atlassian.net/browse/ADA-2704. The hotspot title is announced in the button's aria-label. 
It is related to https://github.com/kaltura/playkit-js-navigation/pull/391, the title being passed from here.
A ticket for translation will be created after approval
Please add a detailed description of the change, weather it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.
> Fix(ADA-2704) - Add title to Hotspot button

- src/timeline-manager.tsx
Issue:
The cue-points of the IVQ questions are loaded when the ads are playing, therefore, they are not seen in the seek bar when the entry is playing.
Fix:
When all the ads are completed, remove all the cue-points and put them again, in order to see them on the seekbar.
solved [SUP-47479](https://kaltura.atlassian.net/browse/SUP-47479)
[SUP-47479]: https://kaltura.atlassian.net/browse/SUP-47479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(SUP-47479): player with bumper prevents display of quiz timestamp on the timeline
